# numpy library

<span style='font-family:XB Niloofar;font-size:17px'>
NumPy یک کتابخانه برای زبان برنامه نویسی پایتون (Python) است. با استفاده از این کتابخانه امکان استفاده از آرایه‌ها و ماتریس‌های بزرگ چند بعدی فراهم می‌شود. هم‌چنین می‌توان از تابع‌های ریاضیاتی سطح بالا بر روی این آرایه‌ها استفاده کرد.


<span style='font-family:XB Niloofar;font-size:17px'>
سرعت اجرا در آرایه ها بسیار بیشتر از لیست است چون آرایه ها Locally Refrence هستند یعنی حافظه از جایی که خونده برمیگرده و دوباره همانجا را میخونه

<span style='font-family:XB Niloofar;font-size:17px'>
حال به بررسی توابع پرکاربرد در numpy می پردازیم :

<span style='font-family:XB Niloofar;font-size:17px'>
برای شروع کار با numpy ابتدا لازم است کتابخانه آن را به کد اضافه کنیم :  
      
سپس باید یک object برای آن تعیین کنیم که توابع را به کمک آن فراخوانی کنیم :

In [1]:
import numpy as np

<span style='font-family:XB Niloofar;font-size:17px'>
ابتدا یک آرایه ساده با دستور np.array درست میکنیم :

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

<span style='font-family:XB Niloofar;font-size:17px'>
برای اینکه مشخصات ابعادی آرایه را ببینیم : 

In [5]:
a.shape

(3,)

<span style='font-family:XB Niloofar;font-size:17px'>
برای اینکه تعداد بعد را پیدا کنیم :

In [6]:
a.ndim

1

<span style='font-family:XB Niloofar;font-size:17px'>
برای اینکه تعداد المان آرایه را پیدا کنیم :

In [7]:
a.size

3

<span style='font-family:XB Niloofar;font-size:17px'>
حال یک آرایه بزرگتر درست تر میکنیم ، میتوان با استفاده از dtype تایپ المان هارا مشخص کرد :

In [8]:
b = np.array([[1.2,2,3],[4,5,6]],dtype = int)

In [9]:
b

array([[1, 2, 3],
       [4, 5, 6]])

<span style='font-family:XB Niloofar;font-size:17px'>
با تابع arange میتوان بین دو عدد با فاصله دلخواه آرایه ایجاد کرد :

In [10]:
b = np.arange(start=1,stop=10,step=1)

In [11]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

<span style='font-family:XB Niloofar;font-size:17px'>
اگر step را خودمان مشخص نکنیم ، به طور پیش فرض یک در نظر میگیرد :

In [12]:
b = np.arange(start=1,stop=10)

In [14]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

<span style='font-family:XB Niloofar;font-size:17px'>
اگر بخواهیم ابعاد ماتریس را تغییر دهیم از تابع reshape استفاده میکنیم :

In [15]:
b.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

<span style='font-family:XB Niloofar;font-size:17px'>
با تابع linspace میتوان بین دو عدد ، به هر تعداد که میخواهیم عدد بگذاریم :

In [16]:
np.linspace(start=10,stop=20,num=20)

array([10.        , 10.52631579, 11.05263158, 11.57894737, 12.10526316,
       12.63157895, 13.15789474, 13.68421053, 14.21052632, 14.73684211,
       15.26315789, 15.78947368, 16.31578947, 16.84210526, 17.36842105,
       17.89473684, 18.42105263, 18.94736842, 19.47368421, 20.        ])

<span style='font-family:XB Niloofar;font-size:17px'>
با تابع np.ones میتوان ماتریس یک را درست کرد :  
        
درون پرانتز هم میتوان shape  آن را تعیین کرد

In [17]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

<span style='font-family:XB Niloofar;font-size:17px'>
با تابع np.zeros میتوان ماتریس صفر درست کرد :

In [18]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

<span style='font-family:XB Niloofar;font-size:17px'>
با تابع np.random.random میتوان بین صفر تا یک نسبت به  shape رندوم درست کند :

In [19]:
np.random.random((3,4))

array([[0.11876746, 0.72572213, 0.55592661, 0.18030981],
       [0.22636962, 0.60676775, 0.71265427, 0.37305257],
       [0.94606954, 0.13135218, 0.48850161, 0.3640879 ]])

<span style='font-family:XB Niloofar;font-size:17px'>
با تابع np.random.randint میتوان بین دو عدد با shape دلخواه عدد تصادفی درست کند :

In [21]:
c=np.random.randint(0,10,(3,3))

In [22]:
c

array([[5, 0, 6],
       [0, 6, 0],
       [0, 6, 8]])

<span style='font-family:XB Niloofar;font-size:17px'>
برای دسترسی به المان یک ماتریس از الگوی زیر استفاده میکنیم :

In [24]:
c[2][2]

8

<span style='font-family:XB Niloofar;font-size:17px'>
الگوی نامپای به این شکل است که اول سطر را قبول میکند سپس ستون را 

<span style='font-family:XB Niloofar;font-size:17px'>
برای اسلایس کردن ماتریس از الگوی زیر استفاده میکنیم :  
      
همیشه stop-1 میشود و تا خود آن عدد جلو نمیرود

In [25]:
a = np.arange(1,21)

In [26]:
a.shape = (4,5)

In [27]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [29]:
a[1:3,2:4]

array([[ 8,  9],
       [13, 14]])

<span style='font-family:XB Niloofar;font-size:17px'>
میتوان در یک ماتریس بزرگ و کوچک تر از یک عددی را پیدا کنیم :  

In [33]:
d = np.random.randint(0,50,size =(3,5))

In [34]:
d

array([[10, 49, 36, 19, 39],
       [45, 25, 20, 13,  5],
       [ 4, 29, 15, 41, 34]])

In [35]:
d[d>30]

array([49, 36, 39, 45, 41, 34])

<span style='font-family:XB Niloofar;font-size:17px'>
برای اینکه یک ماتریس قطری درست کنیم :

In [36]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

<span style='font-family:XB Niloofar;font-size:17px'>
برای اینکه در یک ماتریس بزرگترین المان را پیدا کنیم :

In [37]:
d.max()

49

<span style='font-family:XB Niloofar;font-size:17px'>
اگر بخواهیم به صورت True و False المان های بزرگ تر و کوچک تر را پیدا کنیم : 

In [38]:
d>30

array([[False,  True,  True, False,  True],
       [ True, False, False, False, False],
       [False, False, False,  True,  True]])

<span style='font-family:XB Niloofar;font-size:17px'>
ما در نامپای ماتریس چند بعدی هم میتوانیم داشته باشیم :

In [39]:
np.random.randint(1,60,size=(2,3,5))

array([[[31, 17, 25, 39, 46],
        [41, 16,  4,  3, 57],
        [26, 35,  6, 40, 24]],

       [[59, 55, 53, 46, 11],
        [13, 39, 27, 18, 17],
        [25, 26, 50, 22,  5]]])

<span style='font-family:XB Niloofar;font-size:17px'>
به خاطر dynamic بودن زبان پایتون میتوان المان های ماتریس را هم تغییر داد ، میتوان از متد اسلایسینگ استفاده کرد :

In [40]:
d

array([[10, 49, 36, 19, 39],
       [45, 25, 20, 13,  5],
       [ 4, 29, 15, 41, 34]])

In [43]:
d[2,2]=100

In [50]:
d[:3,2]=100

In [51]:
d

array([[ 10,  49, 100,  19,  39],
       [ 45,  25, 100,  13,   5],
       [100, 100, 100,  41,  34]])

<span style='font-family:XB Niloofar;font-size:17px'>
میتوان بین دو ماتریس عملیات ریاضی و منطقی انجام داد به شرط اینکه ابعاد آن مناسب عملیات ریاضی باشد :

In [52]:
a = np.arange(1,101,1).reshape(10,10)

In [71]:
b = np.linspace(1,100,100).reshape(10,10)

In [72]:
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [73]:
b

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
       [ 21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.],
       [ 31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.],
       [ 41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.],
       [ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.],
       [ 71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.],
       [ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.]])

In [74]:
a + b

array([[  2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.],
       [ 22.,  24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.],
       [ 42.,  44.,  46.,  48.,  50.,  52.,  54.,  56.,  58.,  60.],
       [ 62.,  64.,  66.,  68.,  70.,  72.,  74.,  76.,  78.,  80.],
       [ 82.,  84.,  86.,  88.,  90.,  92.,  94.,  96.,  98., 100.],
       [102., 104., 106., 108., 110., 112., 114., 116., 118., 120.],
       [122., 124., 126., 128., 130., 132., 134., 136., 138., 140.],
       [142., 144., 146., 148., 150., 152., 154., 156., 158., 160.],
       [162., 164., 166., 168., 170., 172., 174., 176., 178., 180.],
       [182., 184., 186., 188., 190., 192., 194., 196., 198., 200.]])

In [75]:
a - b 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

<span style='font-family:XB Niloofar;font-size:17px'>
برای این که میانگین یک ماتریس را بدست آوریم :

In [77]:
np.mean(a)

50.5

<span style='font-family:XB Niloofar;font-size:17px'>
برای این که میانه یک ماتریس را بدست آوریم :

In [78]:
np.median(a)

50.5

<span style='font-family:XB Niloofar;font-size:17px'>
برای این که واریانس یک ماتریس را بدست آوریم :

In [79]:
np.var(a)

833.25

<span style='font-family:XB Niloofar;font-size:17px'>
برای این که انحراف معیار یک ماتریس را بدست آوریم :

In [80]:
np.std(a)

28.86607004772212

<span style='font-family:XB Niloofar;font-size:19px'>
حالا به بررسی مهم تفاوت copy,view,= در نامپای می پردازیم :

<span style='font-family:XB Niloofar;font-size:17px'>
اگر دو ماتریس را برابر هم قرار دهیم هر دو در یک مکان حافظه قرار میگیرند و اگر در یکی تغییر اعمال کنیم در دومی هم تغییر اعمال میشود :

In [81]:
d = np.random.randint(0,50,size =(3,5))

In [83]:
d

array([[38,  6, 49, 39, 37],
       [31, 43, 17, 32,  1],
       [49, 29, 18, 32,  5]])

In [85]:
d = a

In [87]:
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [88]:
d

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [89]:
a[2][4]=100

In [90]:
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24, 100,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [91]:
d

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24, 100,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

<span style='font-family:XB Niloofar;font-size:17px'>
اگر از view استفاده کنیم برای مساوی در یک مکان حافظه قرار نمی گیرند ولی اگر تغییری اعمال کنیم در دومی هم تغییر اعمال میشود 

<span style='font-family:XB Niloofar;font-size:17px'>
اگر از copy استفاده کنیم ، نه در یک حافظه قرار میگیرند و نه در یکی تغییر اعمال کنیم در دیگری اعمال منشود